name: Deploy Next.js in Docker on VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Sync Project to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=600 -o ServerAliveInterval=60 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "mkdir -p ~/next-app"
        rsync -avz --exclude node_modules --exclude .git ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:~/next-app

    - name: Create .env on VPS
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=600 -o ServerAliveInterval=60 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          cat > ~/next-app/.env <<EOL
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET=${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          SANITY_API_TOKEN=${{ secrets.SANITY_API_TOKEN }}
          NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
          EOL
        EOF

    - name: Build and Run Docker Container on VPS
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=600 -o ServerAliveInterval=60 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/next-app

          # Stop and remove old container if exists
          docker stop next-app || true
          docker rm next-app || true

          # Build new image (env is present inside the context)
          docker build --no-cache -t next-app .

          # Run the container
          docker run -d -p 3000:3000 --name next-app --restart always next-app
        EOF
